### PR TITLE
Fix `warp` cheatcode

### LINKED ISSUE #235: Timestamp and block number start very low
I'm logging the timestamp and block numbers here:
```
 => [event] Debug0("block.timestamp", 2)
 => [event] Debug0("block.number", 2)
```

This causes a problem for my fuzzing setup because I want to schedule events in the past, which gives me an underflow if I try to calculate them.

I've tried using the `warp` and `roll` cheatcodes in the constructor but got the following error:
```
error Failed to initialize the test chain
‣ contract deployment tx returned a failed status: execution reverted
```

### PR DESCRIPTION
**Pull request by anishnaik**
Our `warp` cheatcode accepted a `uint64` even though the official cheatcode intakes a `uint256`. This PR fixes that.
This PR closes #235

### CODE REVIEW

File: chain/standard_cheat_code_contract.go [hunk 1]
```diff
@@ -67,13 +67,23 @@ func getStandardCheatCodeContract(tracer *cheatCodeTracer) (*CheatCodeContract,
...
+		"warp", abi.Arguments{{Type: typeUint256}}, abi.Arguments{},
 		func(tracer *cheatCodeTracer, inputs []any) ([]any, *cheatCodeRawReturnData) {
 			// Maintain our changes until the transaction exits.
-			original := tracer.evm.Context.Time
-			tracer.evm.Context.Time = inputs[0].(uint64)
+			originalTime := tracer.evm.Context.Time
+
+			// Retrieve new timestamp and make sure it is LEQ max value of an uint64
+			newTime := inputs[0].(*big.Int)
+			_, uint64Max := utils.GetIntegerConstraints(false, 64)
```
Comment (Xenomega) [inline chain/standard_cheat_code_contract.go:77]: This works, I'm fine with it, but maybe even better would be to make this global, so it doesn't need to be recomputed each time. Should be dirt cheap though, so I'm fine with it.

File: fuzzing/testdata/contracts/cheat_codes/vm/warp.sol [hunk 2]
```diff
@@ -1,6 +1,6 @@
 // This test ensures that the block timestamp can be set with cheat codes
 interface CheatCodes {
-    function warp(uint64) external;
+    function warp(uint256) external;
```
Comment (Xenomega) [inline fuzzing/testdata/contracts/cheat_codes/vm/warp.sol:3]: Question, should we leave compatibility for both uint256 and uint64 in case someone is already dependent on uint64, or do you think it doesn't matter? That's the only thing I thought worth mentioning here.

Comment (anishnaik) [reply fuzzing/testdata/contracts/cheat_codes/vm/warp.sol:3]: Given that most people use Foundry, they will already have an interface setup to use with medusa and I doubt they will add the `warp(uint64)` function signature. So, we _can_, but I don't think it will serve any major value since most people will use HEVM's or Foundry's predefined interface.

File: chain/standard_cheat_code_contract.go (hunk 1 above)
Comment (anishnaik) [reply chain/standard_cheat_code_contract.go]: Updated in [8922a67](https://github.com/crytic/medusa/pull/255/commits/8922a6781d101d4486cd688e8dbfe5faa058a21d)

File: fuzzing/testdata/contracts/cheat_codes/vm/warp.sol (hunk 2 above)
Comment (anishnaik) [reply fuzzing/testdata/contracts/cheat_codes/vm/warp.sol:3]: The primary thing we have to do is make sure we highlight this deviation in our documentation, which I have made note of.

Comment (Xenomega) [reply fuzzing/testdata/contracts/cheat_codes/vm/warp.sol:3]: Awesome, thanks for the context :)

**Review by Xenomega — APPROVED** [review]
bing bong
