### PR TITLE
Fix panic when execution tracing cheatcode contracts

### LINKED ISSUE #410: panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference

I keep getting this runtime error when I try to run my test. 

```
panic: runtime error: invalid memory address or nil pointer dereference

    panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xca727b]
```

The contract compiles and shows signs that it is about to start fuzzing, but it doesn't progress beyond zero sequences (breaks on 1 seq/s). Something like this: `⇾ fuzz: elapsed: 1m23s, calls: 135 (41/sec), seq/s: 1, coverage: 8`. I don't get the error with Echidna and Foundry.

Unfortunately, I can't publicly share the repo but I am confident the issue isn't with the setup.

For additional context, please check out my [Echidna issue submission.](https://github.com/crytic/echidna/issues/1296#issuecomment-2246922806)

Medusa version: 0.1.5
Slither version: 0.10.3

The full error:
<details>
```
⇾ fuzz: elapsed: 1m23s, calls: 135 (41/sec), seq/s: 1, coverage: 8

panic: runtime error: invalid memory address or nil pointer dereference

	panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xca727b]



goroutine 12649 [running]:

github.com/crytic/medusa/fuzzing/executiontracer.(*ExecutionTracer).OnTxEnd(...)

	github.com/crytic/medusa/fuzzing/executiontracer/execution_tracer.go:113

github.com/crytic/medusa/chain/vendored.EVMApplyTransaction.func1()

	github.com/crytic/medusa/chain/vendored/apply_transaction.go:45 +0x35

panic({0xe75d20?, 0x17cb640?})

	runtime/panic.go:770 +0x132

github.com/crytic/medusa/chain.getStandardCheatCodeContract.func13(0xc00e886140, {0xc00217fd60, 0x1, 0x1})

	github.com/crytic/medusa/chain/standard_cheat_code_contract.go:248 +0x57

github.com/crytic/medusa/chain.(*CheatCodeContract).Run(0xc0005f8008, {0xc01e9f5640, 0x24, 0x40})

	github.com/crytic/medusa/chain/cheat_code_contract.go:180 +0x103

github.com/ethereum/go-ethereum/core/vm.RunPrecompiledContract({0x11abd00, 0xc0005f8008}, {0xc01e9f5640, 0x24, 0x40}, 0x1742fa0, 0xc00d2085a0)

	github.com/ethereum/go-ethereum@v1.14.6/core/vm/contracts.go:204 +0xb3

github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc00d571e00, {0x11a9f80, 0xc00cdf5ad0}, {0x71, 0x9, 0x70, 0x9e, 0xcf, 0xa9, 0x1a, ...}, ...)

	github.com/ethereum/go-ethereum@v1.14.6/core/vm/evm.go:233 +0x651

github.com/ethereum/go-ethereum/core/vm.opCall(0x1?, 0xc00d550660, 0xc0102c6f18)

	github.com/ethereum/go-ethereum@v1.14.6/core/vm/instructions.go:683 +0x576

github.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run(0xc00d550660, 0xc00cdf5ad0, {0xc00e003ea0, 0x44, 0x50}, 0x0)

	github.com/ethereum/go-ethereum@v1.14.6/core/vm/interpreter.go:304 +0xc9c

github.com/ethereum/go-ethereum/core/vm.(*EVM).Call(0xc00d571e00, {0x11a9a20, 0xc00d574240}, {0xa6, 0x47, 0xff, 0x3c, 0x36, 0xcf, 0xab, ...}, ...)

	github.com/ethereum/go-ethereum@v1.14.6/core/vm/evm.go:249 +0x948

github.com/ethereum/go-ethereum/core.(*StateTransition).TransitionDb(0xc02770b268)

	github.com/ethereum/go-ethereum@v1.14.6/core/state_transition.go:445 +0x805

github.com/ethereum/go-ethereum/core.ApplyMessage(0x65025c79c4d55a2b?, 0x215e217a7c31f814?, 0xcfd6cc8d?)

	github.com/ethereum/go-ethereum@v1.14.6/core/state_transition.go:184 +0x57

github.com/crytic/medusa/chain/vendored.EVMApplyTransaction(0xc00c4573f0, 0xc00058a820, 0xc0004299f8, 0x57cb2?, 0xc01e8b1fb0, 0xc00bc26340, 0xc00ca6b760, {0x68, 0xbf, 0x11, ...}, ...)

	github.com/crytic/medusa/chain/vendored/apply_transaction.go:54 +0x273

github.com/crytic/medusa/chain.(*TestChain).PendingBlockAddTx(0xc01630a3c0, 0xc00c4573f0, 0x57cb2?)

	github.com/crytic/medusa/chain/test_chain.go:778 +0x48f

github.com/crytic/medusa/fuzzing/calls.ExecuteCallSequenceIteratively(0xc01630a3c0, 0xc02770bb90, 0x0, 0xc02770bbb0)

	github.com/crytic/medusa/fuzzing/calls/call_sequence_execution.go:93 +0x3dd

github.com/crytic/medusa/fuzzing/calls.ExecuteCallSequenceWithExecutionTracer(0xc01630a3c0, {0xc007f35b08, 0xe7, 0x11f}, {0xc0174ace58, 0x1, 0x1}, 0x0)

	github.com/crytic/medusa/fuzzing/calls/call_sequence_execution.go:192 +0x55a

github.com/crytic/medusa/fuzzing.(*PropertyTestCaseProvider).callSequencePostCallTest.func2(0xc0080ec6c0, {0xc0174ace58, 0x1, 0x1}, 0x0)

	github.com/crytic/medusa/fuzzing/test_case_property_provider.go:316 +0xee

github.com/crytic/medusa/fuzzing.(*FuzzerWorker).shrinkCallSequence(0xc0080ec6c0, {0xc012cc7100?, 0xc0080ec6c0?, 0xc01630a3c0?}, {0xc00e8dc8e8?, 0xc00bb22ed0?, 0x2?})

	github.com/crytic/medusa/fuzzing/fuzzer_worker.go:521 +0x18c

github.com/crytic/medusa/fuzzing.(*FuzzerWorker).run(0xc0080ec6c0, 0x11b5640?)

	github.com/crytic/medusa/fuzzing/fuzzer_worker.go:613 +0x5e5

github.com/crytic/medusa/fuzzing.(*Fuzzer).spawnWorkersLoop.func1({0xb43624?, 0xc01189a960?})

	github.com/crytic/medusa/fuzzing/fuzzer.go:640 +0x169

created by github.com/crytic/medusa/fuzzing.(*Fuzzer).spawnWorkersLoop in goroutine 1

	github.com/crytic/medusa/fuzzing/fuzzer.go:623 +0x1d3

```
</details>

### PR DESCRIPTION
**Pull request by anishnaik**
Closes #410.

There was a bug when execution tracing a transaction that would override the tracers that were attached to the EVM instance. Thus, the cheatcode tracer was not attached when execution tracing. When something like `prank` was called, the code would be unable to use the cheatcode tracer which would cause a panic. 

The fix required updating the Test Chain APIs to accept any additional tracers that need to be attached before EVM execution. These tracers are appended and do not override the original set.

### CODE REVIEW

File: chain/test_chain.go [hunk 1]
```diff
@@ -757,12 +748,20 @@ func (t *TestChain) PendingBlockAddTx(message *core.Message, getTracerFn func(tx
...
-	tracer := getTracerFn(len(t.pendingBlock.Messages), tx.Hash())
-	if tracer != nil {
-		vmConfig.Tracer = tracer.Hooks
+	// Figure out whether we need to attach any more tracers
+	var extendedTracerRouter *TestChainTracerRouter
+	if len(additionalTracers) > 0 {
+		// If we have more tracers, extend the transaction tracer router's tracers with additional ones
+		extendedTracerRouter = NewTestChainTracerRouter()
+		extendedTracerRouter.AddTracer(t.transactionTracerRouter.NativeTracer())
+		t.transactionTracerRouter.AddTracers(additionalTracers...)
```
Comment (0xalpharush) [inline chain/test_chain.go:757]:
```suggestion
		// If we have more tracers, extend the transaction tracer router's tracers with additional ones
		extendedTracerRouter = NewTestChainTracerRouter()
		extendedTracerRouter.AddTracer(t.transactionTracerRouter.NativeTracer())
		extendedTracerRouter.AddTracers(additionalTracers...)
```

Comment (0xalpharush) [reply chain/test_chain.go:757]: I think we don't want to preserves side-effects by modifying the `transactionTracerRouter`, right?

**Review by 0xalpharush — APPROVED** [review]
